Restrict allowed methods on action endpoints
unicef/etools pull request #2795
Opened 2020-09-22 15:24 UTC by reinbach

[ch22437]

No longer allow POST requests

2020-09-23 07:55 UTC, roman-karpovich approved these changes

2020-09-28 14:18 UTC, robertavram requested changes

2020-09-28 14:18 UTC, robertavram commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +        request.data.update({"status": Intervention.TERMINATED})
pending updates

2020-09-28 19:15 UTC, reinbach commented on src/etools/applications/partners/serializers/interventions_v3.py
> +                    available_actions.append("cancel")
:+1:

2020-09-28 19:15 UTC, reinbach commented on src/etools/applications/partners/serializers/interventions_v3.py
> +            # need to add terminate action for Senior Management team
:+1:

2020-09-28 19:15 UTC, reinbach commented on src/etools/applications/partners/models.py
> +        pass
:+1:

2020-09-28 19:16 UTC, reinbach commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +
:+1:

2020-09-28 19:16 UTC, reinbach commented on src/etools/applications/partners/serializers/interventions_v3.py
> +            if self._is_management():
:+1:

2020-09-28 19:28 UTC, reinbach commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +        request.data.update({"status": Intervention.TERMINATED})
:+1:

2020-09-29 08:21 UTC, roman-karpovich approved these changes

2020-09-29 14:21 UTC, merged