[ePD] Check and remove dependencies from profile.partner_staff_member field
unicef/etools pull request #2803
Opened 2020-09-25 08:24 UTC by roman-karpovich

2020-09-29 13:50 UTC, reinbach approved these changes
Besides a couple suggestions and question all looks good to me

2020-09-29 13:50 UTC, reinbach commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +    admin = User.objects.order_by('id').first()
Do we know which user this is in all the env with first id?
Any impact on the user being associated to a bunch of staff member records?

2020-09-29 14:45 UTC, robertavram requested changes
haven't finished going through, but can you fix a couple of comment things, and can you move this pr and make it against develop.

2020-09-29 14:45 UTC, robertavram commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +            models.Q(id=profile._partner_staff_member) | models.Q(email__iexact=profile.user.email)
please remove the `models.Q(id=profile._partner_staff_member)` as it can match badly across schemas.. keep only email, don't do exact on email as we have lowered the email addresses everywhere.

2020-09-29 14:45 UTC, robertavram commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +        print('Unable to user for {}; moving to {}'.format(staff_member, admin))
let's not print anything here and run a script to check after... since this will be running on every schema, the first schemas might print out thousands of records.

2020-09-30 14:07 UTC, robertavram commented on src/etools/applications/partners/serializers/partner_organization_v2.py
> +                username=validated_data['email'], email=validated_data['email'], is_staff=False
let's add name and last name any other fields that are present.

2020-09-30 14:09 UTC, robertavram commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +        staff_member.user = admin
create new user if needed.

2020-10-01 13:03 UTC, roman-karpovich commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +        staff_member.user = admin
updated

2020-10-01 13:03 UTC, roman-karpovich commented on src/etools/applications/partners/serializers/partner_organization_v2.py
> +                username=validated_data['email'], email=validated_data['email'], is_staff=False
updated

2020-10-01 13:03 UTC, roman-karpovich commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +            models.Q(id=profile._partner_staff_member) | models.Q(email__iexact=profile.user.email)
updated

2020-10-01 13:03 UTC, roman-karpovich commented on src/etools/applications/partners/migrations/0066_auto_20200924_1453.py
> +    admin = User.objects.order_by('id').first()
updated; creating user if not exists

2020-10-01 13:04 UTC, roman-karpovich commented on src/etools/applications/partners/permissions.py
> +                PartnerStaffMember.get_id_for_user(user) in \
added wrapper to the partner model for this

2020-10-01 13:04 UTC, roman-karpovich commented on src/etools/applications/partners/permissions.py
> +        has_access = user.is_staff or is_user_in_groups(user, ['Partnership Manager'])
done

2020-10-01 13:05 UTC, roman-karpovich commented
epd based version of #2822

2020-10-20 09:38 UTC, roman-karpovich commented
update epd from develop to minimize changes list. right now there are many commits from develop

2020-11-10 11:05 UTC, roman-karpovich commented
duplicate of #2887

2020-11-10 11:05 UTC, closed without merging