[ePD] Update agreement permission
unicef/etools pull request #2814
Opened 2020-09-29 19:11 UTC by reinbach

2020-09-30 08:10 UTC, roman-karpovich approved these changes

2020-09-30 19:22 UTC, reinbach commented on src/etools/applications/partners/views/interventions_v3.py
> -class APIActionsMixin:
@roman-karpovich I'm thinking of removing this mixin, as I see that it's an abstraction that is really just converting the methods (GET, POST, etc) to another label and then attempting to separate list/retrieve, but not sure we would need to differentiate those 2 in permissions?

Is there something else I'm missing that this mixin is doing?

Would need to update the relevant `view_action_permission`, etc if we removed this mixin.

2020-10-01 13:48 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v3.py
> -class APIActionsMixin:
yes, mixin can be removed without big problems. the main reason is readability, actions are just easier to operate with

2020-10-01 20:40 UTC, robertavram requested changes

2020-10-01 20:40 UTC, robertavram commented on src/etools/applications/partners/permissions.py
> +        'update',
update and partial update should move on line 473

2020-10-02 12:52 UTC, reinbach commented on src/etools/applications/partners/permissions.py
> +        'update',
Sorry forgot to do that

2020-10-05 14:16 UTC, merged