[ePD] Add total UNICEF cash amount without HQ contribution
unicef/etools pull request #2919
Opened 2020-12-14 12:09 UTC by roman-karpovich

[ch24259]

2020-12-14 15:15 UTC, reinbach approved these changes

2020-12-15 11:43 UTC, roman-karpovich commented
@reinbach please re-check. added total_hq_cash_local field to calculate HQ support amount

2020-12-15 13:55 UTC, reinbach approved these changes

2020-12-17 15:08 UTC, robertavram requested changes
changes to the requirements

2020-12-17 15:08 UTC, robertavram commented on src/etools/applications/partners/models.py
> +    total_unicef_cash_local_wo_hq = models.DecimalField(
this should be the current `self.total_unicef_contribution_local()` however that function must now change names to reflect that this contribution is wo HQ contrib

add another function `self.total_unicef_contribution_local()` that includes the total wo hq and add the hq amt(`total_hq_cash_local`) on top. There is no in-system direct relationship between the hq rate and the hq amt as the hq amt is now impossible to calculate automatically due to the rules.

2020-12-17 15:08 UTC, robertavram commented on src/etools/applications/partners/models.py
> +            self.total_unicef_cash_local_wo_hq = self.total_unicef_cash_local_wo_hq.quantize(decimal.Decimal('.01'))
no need to quantize as the db field sets the two decimals

2020-12-17 15:08 UTC, robertavram commented on src/etools/applications/partners/models.py
> +        if self.intervention.hq_support_cost:
this logic block needs major refactor based on the changes

2021-03-30 21:40 UTC, acory commented
@robertavram @domdinicola  
I tested the integration with FE (https://github.com/unicef/intervention-tab-pages/pull/341) and it works. Ready for merge.

2021-03-31 17:04 UTC, merged