sentry staging 2719 RAMSynchronizer fix
unicef/etools pull request #2952
Opened 2021-02-24 15:16 UTC by domdinicola

2021-02-25 16:06 UTC, robertavram requested changes

2021-02-25 16:06 UTC, robertavram commented on src/etools/applications/reports/synchronizers.py
> +                'name': str(r['INDICATOR_DESCRIPTION'])[:1024],
set to empty string or None rather then the string "None" as there's a filter on line331

2021-02-25 16:06 UTC, robertavram commented on src/etools/applications/reports/synchronizers.py
> +                'target': str(r['INDICATOR_TARGET'])[:255],
an indicator without a target is meaningless, I would suggest to use the same logic as for the name and filter these out.

2021-02-25 16:52 UTC, domdinicola commented on src/etools/applications/reports/synchronizers.py
> +                'name': str(r['INDICATOR_DESCRIPTION'])[:1024],
this was @ntrncic input

2021-02-26 15:45 UTC, ntrncic commented on src/etools/applications/reports/synchronizers.py
> +                'name': str(r['INDICATOR_DESCRIPTION'])[:1024],
I meant only for the baseline. @domdinicola

2021-03-02 16:40 UTC, merged