[EPD] Intervention PRC
unicef/etools pull request #2997
Opened 2021-05-06 07:56 UTC by roman-karpovich

[ch25653]

2021-05-24 17:57 UTC, robertavram requested changes

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/models.py
> +            ((NORW, 'No Review Required'),)
can we change the key to "NOREV"

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/models.py
> +    actions_list = models.TextField(verbose_name=_('Actions List'), blank=True)
What is stored in this field?

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/models.py
> +    started_by = models.ForeignKey(
we don't need started_by and started_date.. it's the same as "submitted_by"

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/permissions.py
> +    EXTRA_FIELDS = ['sections_present', 'pd_outputs', 'final_partnership_review', 'prc_reviews']
really nice! 👍

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/permissions.py
> +                self.user_groups.append('PRC Officer')
super use of the framework!

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/serializers/interventions_v3.py
> +            available_actions.append("prc_review")
can we name this "individual_review"

2021-05-24 17:57 UTC, robertavram commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +                    "submission_date": timezone.now().strftime("%Y-%m-%d"),
This date should come from the user. Maybe a separate action called "accept on behalf of partner" that requires the user to input the submission_date

2021-05-25 08:40 UTC, roman-karpovich commented on src/etools/applications/partners/validation/interventions.py
> +    if not (i.partner_accepted and i.unicef_accepted):
nope. permission matrix don't work with booleans properly

2021-05-25 08:40 UTC, roman-karpovich commented on src/etools/applications/partners/validation/interventions.py
> +    if not i.review or (i.review and i.review.overall_approval is not None):
removed tricky part, so comment is not needed anymore;
removed auto transition

2021-05-25 08:45 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +    actions_list = models.TextField(verbose_name=_('Actions List'), blank=True)
i don't remember tbh, paragraph 7 from document

> ‘Action List’ card
> A textbox editable by the PRC secretary while the review is pending and by the Overall Approver

2021-05-25 08:47 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +        return self.reviews.order_by('id').last()
yeah, this will give same result. i can update if you want

2021-05-25 08:48 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +    started_date = models.DateField(null=True, blank=True, verbose_name=_('Date Review Started'))
started date contains date when intervention moved to review status. it's different from submitted date (review approve/reject date)

2021-05-25 08:48 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +    started_by = models.ForeignKey(
started date contains date when intervention moved to review status. it's different from submitted date (review approve/reject date)

2021-05-25 08:49 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +                    "submission_date": timezone.now().strftime("%Y-%m-%d"),
previously we decided to do those changes in separate card (ch25860)

2021-05-25 08:51 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v3_actions.py
> +                    "submission_date": timezone.now().strftime("%Y-%m-%d"),
changes here to cover case when UNICEF create PD and then ask partner to accept

2021-05-25 09:03 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +def update_review_info(i, old_instance=None, user=None):
updated

2021-05-25 09:03 UTC, roman-karpovich commented on src/etools/applications/partners/models.py
> +            ((NORW, 'No Review Required'),)
updated

2021-05-25 09:03 UTC, roman-karpovich commented on src/etools/applications/partners/serializers/interventions_v3.py
> +            available_actions.append("prc_review")
updated

2021-05-25 13:56 UTC, robertavram commented on src/etools/applications/partners/models.py
> +    started_date = models.DateField(null=True, blank=True, verbose_name=_('Date Review Started'))
no need for this one now

2021-06-07 14:58 UTC, robertavram commented
@roman-karpovich tests are failing

2021-06-07 20:31 UTC, robertavram approved these changes

2021-06-07 20:31 UTC, merged