[ePD] Add `Accept on behalf of Partner` action for UNICEF user
unicef/etools pull request #3014
Opened 2021-06-11 07:37 UTC by roman-karpovich

[ch25860]

2021-06-16 14:14 UTC, robertavram requested changes
need some sort of field to indicate that the PD was accepted on behalf of partner

2021-06-17 14:54 UTC, robertavram commented
@roman-karpovich and progress on this

2021-06-17 18:42 UTC, roman-karpovich commented
> @roman-karpovich and progress on this

yes, sorry for delay. updated fields, fixed tests

2021-06-18 16:30 UTC, robertavram approved these changes

2021-06-18 16:30 UTC, merged