[ePD] Connect FR, Amendments, Signature&Dates, Partner Reporting Requirements to permissions.view
unicef/etools pull request #3125
Opened 2021-11-02 12:07 UTC by roman-karpovich

[ch25946]

2021-11-09 20:12 UTC, robertavram requested changes
frs should be viewable and editable by unicef in draft.

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/permission_matrix/intervention_permissions.csv
> +3.9.8,frs,*,,Draft,View,FALSE
frs should be viewable in draft

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/tests/test_api_interventions.py
> -            "frs",
frs should be editable in draft, review, signature and signed

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/tests/test_epd_management/test_funds_reservation.py
> -            reverse('pmp_v3:intervention-detail', args=[self.draft_intervention.pk]),
keep it a draft for FRs

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/tests/test_epd_management/test_funds_reservation.py
> -            reverse('pmp_v3:intervention-detail', args=[self.draft_intervention.pk]),
keep at draft

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/tests/test_epd_management/test_funds_reservation.py
> -                intervention=self.draft_intervention,
keep at draft everywhere, FRs should be editable in draft

2021-11-09 20:12 UTC, robertavram commented on src/etools/applications/partners/permission_matrix/intervention_permissions.csv
> -3.9.8,frs,Unicef Focal Point,,Draft,Edit,TRUE
keep edit true for draft for FRs

2021-11-11 13:34 UTC, roman-karpovich commented
reverted frs-related changes

2022-01-05 19:39 UTC, merged