[ePD] 0.00 totals displayed after adding/editing Result Structure PD Activities
unicef/etools pull request #3131
Opened 2021-11-08 08:53 UTC by roman-karpovich

2021-11-09 19:48 UTC, robertavram requested changes
we can remove the command

2021-11-09 19:48 UTC, robertavram commented on src/etools/applications/reports/management/commands/fix-activity-totals.py
> +import logging
we can get rid of this as it's not supposed to happen typically. Initially i can run something similar manually if needed

2021-11-09 19:48 UTC, robertavram commented on src/etools/applications/reports/serializers/v2.py
> +            attrs.pop('cso_cash', None)
👍

2021-11-11 13:28 UTC, roman-karpovich commented on src/etools/applications/reports/management/commands/fix-activity-totals.py
> +import logging
okay. i thought it will be good to have this part tested if we'll need to run it

2021-11-16 08:27 UTC, roman-karpovich commented on src/etools/applications/reports/management/commands/fix-activity-totals.py
> +import logging
removed

2021-11-16 19:41 UTC, merged