[ePD] Amendments: Sites added in Geographical Coverage in amendment mode are not showed as Difference in Amendment details
unicef/etools pull request #3148
Opened 2021-12-02 14:54 UTC by roman-karpovich

2022-01-05 19:33 UTC, robertavram requested changes

2022-01-05 19:33 UTC, robertavram commented on src/etools/applications/partners/amendment_utils.py
> -        'sites',
it's correct to have sites as IGNORED_FIELD. we should not change sites in the amendment. Sites like programmatic visits are editable at any point in the PD directly.

2022-01-05 19:34 UTC, robertavram commented
I am updating the ticket

2022-01-10 15:19 UTC, roman-karpovich commented
updated. now sites should not be available during amendment mode (read/write permissions are False)

2022-04-08 15:14 UTC, merged