[ch27976] Fix bug on update one for spot check
unicef/etools pull request #3187
Opened 2022-01-17 16:00 UTC by emaciupe

2022-01-17 20:33 UTC, domdinicola requested changes

2022-01-17 20:33 UTC, domdinicola commented on src/etools/applications/partners/models.py
> +            partner=self
I think spot checks from T2F are archived (we don't count anymore)

2022-01-17 20:33 UTC, domdinicola commented on src/etools/applications/partners/models.py
> +            t2f_sc1 = t2f_sc.filter(date__quarter=1).count()
pls remove

2022-01-18 07:27 UTC, emaciupe commented on src/etools/applications/partners/models.py
> +            partner=self
@domdinicola From what I see in t2f.models line 280, spot checks are being counted.

2022-01-18 15:53 UTC, emaciupe commented on src/etools/applications/partners/models.py
> +            partner=self
resolved

2022-01-18 15:53 UTC, emaciupe commented on src/etools/applications/partners/models.py
> +            t2f_sc1 = t2f_sc.filter(date__quarter=1).count()
resolved

2022-01-25 19:53 UTC, domdinicola commented on src/etools/applications/audit/models.py
> +        self.partner.update_spot_checks(event_date=self.date_of_draft_report_to_ip)
@robertavram I guess we can remove this line (no need to recalculate either)

2022-01-26 16:03 UTC, domdinicola commented on src/etools/applications/audit/models.py
> +        self.partner.update_spot_checks(event_date=self.date_of_draft_report_to_ip)
remove this line

2022-01-26 17:50 UTC, emaciupe commented on src/etools/applications/audit/models.py
> +        self.partner.update_spot_checks(event_date=self.date_of_draft_report_to_ip)
solved

2022-01-26 19:07 UTC, domdinicola approved these changes

2022-02-02 19:55 UTC, robertavram commented on src/etools/applications/partners/models.py
> +        self.save(update_fields=['hact_values'])
nice one!

2022-02-02 19:55 UTC, merged