[ch28785] flat attachments for FAM and PSEA
unicef/etools pull request #3227
Opened 2022-03-17 22:34 UTC by domdinicola

[ch28785]

2022-03-18 14:46 UTC, domdinicola commented
migrating existing attachments

```
from etools.applications.attachments.models import *
from etools.applications.attachments.utils import *
for country in Country.objects.exclude(schema_name='public'):
    set_country(country)
    for att in AttachmentFlat.objects.filter(source='Financial Assurance (FAM)'):
        att.agreement_reference_number = get_reference_number(att.attachment)
        att.save()
```

2022-03-25 14:26 UTC, emaciupe requested changes

2022-03-25 14:26 UTC, emaciupe commented on src/etools/applications/attachments/utils.py
> +    elif isinstance(obj.content_object, Engagement):
@domdinicola you could remove these lines and extend on line 108 e.g.
```
if isinstance(obj.content_object, (Agreement)):
       return obj.content_object
```
to
```
if isinstance(obj.content_object, (Agreement, Engagement, Assessment)):
       return obj.content_object
```

2022-03-25 16:22 UTC, domdinicola commented on src/etools/applications/attachments/utils.py
> +    elif isinstance(obj.content_object, Engagement):
yep, I guess make sense [I was thinking to have one entry per module but anyways is not the case]

2022-03-25 16:23 UTC, domdinicola commented
@emaciupe did you review also the script?

2022-03-28 13:29 UTC, emaciupe approved these changes
Looks good to me!

2022-04-08 15:21 UTC, merged