[ePD] Validations to be confirmed or developed on partner or unicef accept
unicef/etools pull request #3235
Opened 2022-03-28 10:20 UTC by roman-karpovich

2022-04-06 18:05 UTC, robertavram requested changes

2022-04-06 18:05 UTC, robertavram commented on src/etools/applications/partners/validation/interventions.py
> +def pd_outputs_presented(i):
at least one pd output is present `pd_outputs_present`

2022-04-06 18:05 UTC, robertavram commented on src/etools/applications/partners/validation/interventions.py
> +    return not i.result_links.filter(ram_indicators__isnull=True).exists()
this is supposed to check for PD indicators which are the `AppliedIndicator` model, something like:
`i.result_links.filter(ll_results__applied_indicators__isnull=True)`

2022-04-08 12:47 UTC, roman-karpovich commented on src/etools/applications/partners/validation/interventions.py
> +def pd_outputs_presented(i):
fixed

2022-04-08 13:09 UTC, roman-karpovich commented on src/etools/applications/partners/permission_matrix/intervention_permissions.csv
> -3.13.1,reporting_requirements,*,unicef_not_accepted,Draft,Required,FALSE
configured test to confirm partner has no view permission to this field

2022-04-08 14:50 UTC, roman-karpovich commented on src/etools/applications/partners/validation/interventions.py
> +    return not i.result_links.filter(ram_indicators__isnull=True).exists()
updated

2022-04-13 12:58 UTC, merged