[ePD] Delete of PD related objects doesn’t trigger history capture. There is no snapshot activity record of deleting a pd activity.
unicef/etools pull request #3297
Opened 2022-05-17 12:11 UTC by roman-karpovich

2022-05-23 14:30 UTC, robertavram requested changes
It's looking good so far. a few comments

2022-05-23 14:30 UTC, robertavram commented on src/etools/applications/partners/views/interventions_v2.py
> +        InterventionIsDraftPermission | UserIsUnicefFocalPoint | UserIsPartnershipManagerOrSeniorManager,
InterventionAmendment should only be able to be deleted if:
(the Amendment  is not completed) AND (the user is Intervention UnicefFocalPoint or Intervention Budget Owner)

2022-05-23 14:30 UTC, robertavram commented on src/etools/applications/partners/views/interventions_v2.py
> +    def get_intervention(self) -> Intervention:
no need to use type declaration here as it's clear from the method text that this will return an Intervention, since we didn't set standards on how/when to use type declaration, we should only use this if it's not easily understood what the function will return.

2022-05-23 14:30 UTC, robertavram commented on src/etools/applications/reports/views/v2.py
> +        # do cleanup if pd output still not associated to cp output
nice!

2022-05-30 10:37 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v2.py
> +        InterventionIsDraftPermission | UserIsUnicefFocalPoint | UserIsPartnershipManagerOrSeniorManager,
updated

2022-05-30 10:38 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v2.py
> +    def get_intervention(self) -> Intervention:
removed such declarations from get_interventions methods

2022-05-30 10:38 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v2.py
> +    def get_intervention(self) -> Intervention:
updated

2022-05-30 13:21 UTC, robertavram commented on src/etools/applications/reports/views/v2.py
> +        InterventionIsDraftPermission | UserIsUnicefFocalPoint | UserIsPartnershipManagerOrSeniorManager,
a Partner Staff Member focal point can delete PD Outputs as well. (PartnershipManagerorSeniorManager should not be able to without being a focal point - can be removed)

2022-05-31 04:50 UTC, roman-karpovich commented on src/etools/applications/reports/views/v2.py
> +        InterventionIsDraftPermission | UserIsUnicefFocalPoint | UserIsPartnershipManagerOrSeniorManager,
updated permission classes here to match v3 endpoint which uses permissions matrix

2022-06-03 13:51 UTC, merged