[Develop] chore: [sc-32325] Migrate pd attachments page to unicef_attachments
unicef/etools pull request #3425
Opened 2023-01-27 02:55 UTC by roman-karpovich

Story details: https://app.shortcut.com/unicefetools/story/32325

2023-01-27 03:02 UTC, roman-karpovich commented
@robertavram @domdinicola could we please release updated version of unicef_attachments? PR depends on new migration from there.
https://github.com/unicef/unicef-attachments/pull/37

2023-01-31 19:42 UTC, robertavram commented
https://pypi.org/project/unicef-attachments/0.12/

2023-02-08 09:18 UTC, emaciupe requested changes

2023-02-08 09:18 UTC, emaciupe commented on src/etools/applications/partners/serializers/interventions_v2.py
> +    attachment = serializers.FileField(read_only=True, source='file')
@roman-karpovich attachment and attachment_file are identical here - was attachment meant to be a pk? like in PMPInterventionAttachmentSerializer?

2023-02-08 09:18 UTC, emaciupe commented on src/etools/applications/partners/views/interventions_v3.py
> +            raise ValidationError("Deleting an attachment can only be done in Draft status")
@roman-karpovich please mark the validation message as translatable _("")

2023-02-08 09:18 UTC, emaciupe commented on src/etools/applications/partners/views/interventions_v2.py
>              raise ValidationError("Deleting an attachment can only be done in Draft status")
@roman-karpovich can you also prefix with translatable? seems i missed it. (for views use `from django.utils.translation import gettext as _`)

2023-02-09 01:43 UTC, roman-karpovich commented on src/etools/applications/partners/serializers/interventions_v2.py
> +    attachment = serializers.FileField(read_only=True, source='file')
updated

2023-02-09 01:43 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v3.py
> +            raise ValidationError("Deleting an attachment can only be done in Draft status")
updated

2023-02-09 01:43 UTC, roman-karpovich commented on src/etools/applications/partners/views/interventions_v2.py
>              raise ValidationError("Deleting an attachment can only be done in Draft status")
updated

2023-02-10 09:31 UTC, emaciupe commented
@roman-karpovich I will remove the .po files line numbering from the translations so there will be a lot less failing on test checks

2023-02-10 11:28 UTC, roman-karpovich commented
> @roman-karpovich I will remove the .po files line numbering from the translations so there will be a lot less failing on test checks

agreed. now it's better to revert those changes. localisations were broken at some moment, so i regenerated them. now they are fine in develop

2023-02-13 16:40 UTC, emaciupe approved these changes
Looks good!

2024-09-16 13:10 UTC, closed without merging