[ch32722] ePD-amp changes and fixes
unicef/etools pull request #3427
Opened 2023-01-31 10:29 UTC by emaciupe

Includes: 
1. Add docstring to mapping - code review

2. Activate/Inactivate user when changing realms

3. Fix removing all groups - groups: []

2023-02-14 17:40 UTC, robertavram requested changes

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/audit/views.py
> +                vendor_number__in=['UNICEF', '000']).values_list('id', flat=True),
keep only UNICEF org

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/audit/views.py
> +    filter_backends = (SearchFilter, DjangoFilterBackend)
let's revisit!

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/tpm/tpmpartners/synchronizers.py
> +            country = Country.objects.get(schema_name=defaults['country'] if defaults['country'] else connection.tenant.schema_name)
connection tenant schema

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/tpm/tpmpartners/synchronizers.py
> +            country = Country.objects.get(schema_name=defaults['country'] if defaults['country'] else connection.tenant.schema_name)
i think we need to set this somewhere else

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/tpm/tpmpartners/synchronizers.py
> +                country__in=partner.countries.all(),
country not needed, deactivate all realms (the TPM active groups) in all countries that have this organization. remove country filter

2023-02-14 17:40 UTC, robertavram commented on src/etools/applications/users/serializers_v3.py
> +        organization_id = validated_data.get('organization', self.context['request'].user.profile.organization.id)
if you are a UNICEF User you need to send the organization id if you're not a unicef user, the organization should be taken from the user herself.

2023-03-01 08:58 UTC, emaciupe commented on src/etools/applications/tpm/tpmpartners/synchronizers.py
> +            country = Country.objects.get(schema_name=defaults['country'] if defaults['country'] else connection.tenant.schema_name)
@robertavram there is a dedicated endpoint on partners/id/activate/ that also sets the country

2023-04-25 14:30 UTC, merged