[ch32786] Update attachments permissions
unicef/etools pull request #3438
Opened 2023-02-14 03:20 UTC by roman-karpovich

2023-02-14 03:21 UTC, roman-karpovich commented
linked to https://github.com/unicef/unicef-attachments/pull/40

2023-02-21 13:50 UTC, emaciupe approved these changes

2023-02-22 08:35 UTC, roman-karpovich commented
tests should be fine after 0.13 unicef attachments release. 
https://github.com/unicef/unicef-attachments/pull/40

2024-04-22 00:50 UTC, robertavram requested changes
I love what you did here.. maybe minor tweaks.. I think we're ready to merge this in. Please review comments.

2024-04-22 00:50 UTC, robertavram commented on src/etools/applications/attachments/permissions.py
> +            return content_object.get_related_third_party_users().filter(pk=request.user.pk).exists()
we need to make sure that the user has at least one active realm in the current tenant workspace

2024-04-22 00:50 UTC, robertavram commented on src/etools/applications/attachments/permissions.py
> +            return content_object.get_related_third_party_users().filter(pk=request.user.pk).exists()
maybe one approach is to send in the user to the instance method it return true or false. In some cases the user might have left one party like a Partner org, but may be working with another one in the same workspace. If the user doesn't have an active realm for the associated partner or vendor, etc... to whatever instance we're probing, then we should impose the limitation.

2024-04-22 00:50 UTC, robertavram commented on src/etools/applications/field_monitoring/fm_settings/models.py
> +        return get_user_model().objects.filter(realms__group=FMUser.as_group())
this would be too broad as it filters all realms in the whole world. (may be worth considering a slightly different approach for this method)

2024-04-24 11:26 UTC, roman-karpovich commented on src/etools/applications/field_monitoring/fm_settings/models.py
> +        return get_user_model().objects.filter(groups=FMUser.as_group())
this is related to Field monitoring, so we want to have FMUser group. but in fact field monitor is always UNICEF, so it can be safely removed

2024-04-24 11:27 UTC, roman-karpovich commented on src/etools/applications/attachments/permissions.py
> +            return content_object.get_related_third_party_users().filter(pk=request.user.pk).exists()
added IsActiveInCurrentSchema permission to check this

2024-04-24 11:28 UTC, roman-karpovich commented on src/etools/applications/field_monitoring/fm_settings/models.py
> +        return get_user_model().objects.filter(realms__group=FMUser.as_group())
agreed. removed it as Field monitors are not third party users, so we don't need it

2024-04-24 11:29 UTC, roman-karpovich commented on src/etools/applications/attachments/permissions.py
> +            return content_object.get_related_third_party_users().filter(pk=request.user.pk).exists()
added explicit filters inside

2024-04-29 13:45 UTC, robertavram commented
@roman-karpovich failing tests.

2024-04-29 14:02 UTC, roman-karpovich commented
> linked to [unicef/unicef-attachments#40](https://github.com/unicef/unicef-attachments/pull/40)

depends on https://github.com/unicef/unicef-attachments/pull/40

2024-04-29 14:02 UTC, roman-karpovich commented
> @roman-karpovich failing tests.

depends on https://github.com/unicef/unicef-attachments/pull/40

2024-06-19 08:48 UTC, closed without merging