[hotfix] Location import fix
unicef/etools pull request #3544
Opened 2023-07-20 16:55 UTC by robertavram

2023-07-21 14:03 UTC, emaciupe requested changes

2023-07-21 14:07 UTC, robertavram commented on src/etools/applications/management/views/gis_v1.py
> +            locs = Location.objects.all_with_geom().filter(Q(intervention_flat_locations__isnull=False) |
thanks! we'll have to replace all these.. move them somewhere else

2023-07-21 15:28 UTC, emaciupe approved these changes
looks good!

2023-07-24 10:16 UTC, domdinicola approved these changes

2023-07-24 10:16 UTC, domdinicola approved these changes

2023-07-31 18:23 UTC, merged