[ch35934] New Notification to UNICEF Focal persons
unicef/etools pull request #3624
Opened 2024-01-19 17:54 UTC by emaciupe

[ch35934]

2024-01-23 14:36 UTC, emaciupe commented
requires 
```
./manage.py update_notifications
./manage.py init-celery
```

2024-04-16 16:17 UTC, robertavram requested changes

2024-04-16 16:17 UTC, robertavram commented on src/etools/applications/partners/tasks.py
> +                .filter(agreement__partner=partner)\
exclude closed and ended interventions
exclude draft interventions with modified more than 1 year ago

2024-04-16 16:17 UTC, robertavram commented on src/etools/applications/partners/tasks.py
> +                today - (F('core_values_assessment_date') +
core_values_assessment_date is one, we also need to add `last_assessment_date` if either of those dates surpass the limit, we need to inform the users which assessment is expiring:
last_assessment_date is for `"HACT Assessment"`

2024-04-16 16:17 UTC, robertavram commented on src/etools/applications/partners/tasks.py
> +                .annotate(unicef_focal_point_emails=ArrayAgg('unicef_focal_points__email'))
exclude users that don't have the profile_country set to the current country.

2024-06-05 16:22 UTC, merged